# Generated by Django 4.2.11 on 2024-06-06 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование рецепта')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание рецепта')),
            ],
        ),
    ]
